#!/bin/bash

function sourceif() {
  if [ -z "${1:-}" ]; then
    echo "Error: No directory name provided. Please provide a directory name as argument."
      exit 1
  fi

  if [ ! -d "$1" ]; then
      # shellcheck disable=SC1090
      source "$1"
  fi
}