#!/bin/bash
##################################################
set -ue
source "$(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)/../util/init.bash"
##################################################

"$EDITOR" ~/.ssh/config