#!/bin/bash
##################################################
set -ue
source "$(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)/../util/init.bash"
##################################################

if [ -z "${1:-}" ]; then
  echo "Error: No directory name provided. Please provide a directory name as argument."
    exit 1
fi

if [ ! -d "$1" ]; then
    mkdir "$1"
fi